export const TRENDING_QUERIES = [
  "Draft a research outline on quantum computing",
  "Write a Python script for data cleaning",
  "Generate a professional report abstract",
  "Design a prompt for a futuristic city image",
  "Explain the impact of AI on modern healthcare",
  "Create a marketing strategy for a new SaaS product",
  "Summarize the latest advancements in solid-state batteries",
  "Write a React component for a drag-and-drop file uploader",
  "Develop a business plan for a sustainable fashion brand",
  "Analyze the economic effects of universal basic income",
  "Generate a 5-day workout plan for beginners",
  "Write a SQL query to find the top 10 customers by revenue",
  "Explain the concept of zero-knowledge proofs in cryptography",
  "Design a logo concept for an eco-friendly coffee shop",
  "Draft an email to investors providing a Q3 update",
  "Create a comprehensive guide to urban gardening",
  "Write a short sci-fi story about a rogue AI",
  "Explain the differences between GraphQL and REST APIs",
  "Develop a social media content calendar for a bakery",
  "Analyze the pros and cons of remote work for tech companies",
  "Generate a recipe for a vegan, gluten-free chocolate cake",
  "Write a bash script to automate server backups",
  "Explain the physics behind black holes to a 10-year-old",
  "Design a user onboarding flow for a mobile banking app",
  "Draft a press release for a new product launch",
  "Create a study schedule for the MCAT exam",
  "Write a Python script to scrape data from a website",
  "Explain the history and evolution of the internet",
  "Develop a pricing strategy for a subscription box service",
  "Analyze the environmental impact of electric vehicles",
  "Generate a list of 20 engaging blog post ideas for a travel blog",
  "Write a C++ program to implement a binary search tree",
  "Explain the principles of behavioral economics",
  "Design a landing page layout for a fitness app",
  "Draft a cover letter for a software engineering position",
  "Create a packing list for a 2-week trip to Japan",
  "Write a JavaScript function to debounce user input",
  "Explain the mechanics of CRISPR gene editing",
  "Develop a customer retention strategy for an e-commerce store",
  "Analyze the cultural significance of the Renaissance period"
];
